### PR TITLE
Remove defamatory remark.

### PR DESCRIPTION
**Pull request by Penple**
im offended

### CODE REVIEW

**Comment by mattyokan** [comment]
:billed_cap:

**Comment by viomck** [comment]
We're sorry to hear you're having a bad experience with our product!

In order to complete our Famous Verification Process (FVP), please link your Twitter in this issue thread.

Cheers,
- The wikidumb Team

**Comment by Penple** [comment]
> We're sorry to hear you're having a bad experience with our product!
> 
> In order to complete our Famous Verification Process (FVP), please link your Twitter in this issue thread.
> 
> Cheers,
> 
>     * The wikidumb Team

do not

**Comment by viomck** [comment]
Go ahead and email us at awordwith+wikidumb-fvp-team-2@violet.wtf with your twitter when you get a moment. Until then, we'll close this issue.

Thanks,
The Wikidumb FVP Team (Team 2: The Bat Batch!)

**Pull request closed without merging**
